env:
  global:
    - CC_TEST_REPORTER_ID=a6c42062b5df08f65de21ca4bd613643b5ca41d35360c420b9208381649528e3
language: node_js
node_js:
  - "8.11.3"
<<<<<<< Updated upstream

env:
  - NODE_ENV=test
  global:
    - CC_TEST_REPORTER_ID=44dbbb02e79725901edd551157c725b5d39fb04ab2834133e51ed8d147f3f44d

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:  
  - npm install
  - bundle exec rspec

after_script:  
  - npm run test
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coverage
  - npm run coveralls
||||||| merged common ancestors
=======
<<<<<<< HEAD

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:  
  - npm test

after_script:  
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coverage
  - npm run coveralls
||||||| merged common ancestors
=======

env:
  - NODE_ENV=test
  global:
    - CC_TEST_REPORTER_ID=44dbbb02e79725901edd551157c725b5d39fb04ab2834133e51ed8d147f3f44d

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:  
  - npm install
  - bundle exec rspec

after_script:  
  - npm run test
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coverage
  - npm run coveralls
>>>>>>> 542d0139833a51139878599f3f21a3c0cecf322c
>>>>>>> Stashed changes
