env:
  global:
    - CC_TEST_REPORTER_ID=a6c42062b5df08f65de21ca4bd613643b5ca41d35360c420b9208381649528e3
language: node_js
node_js:
  - "8.11.3"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:  
  - npm test

after_script:  
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coverage
  - npm run coveralls
